status:      wip

context:
    img:     /img/poradna-img-01.jpg
    img_alt: Fotka článku
    link:    poradna-detail
    title:   Jak vyměnit sáček ve vysavači
    text:    Obdrželi jste zásilku sáčků VACS? V několika krocích vám poradíme, jak vyměnit sáčky do vysavače a jak vyměnit filtr ve vysavači. Není to nic těžkého a zvládne to každý. Ať už máte vysavač Eta, Zelmer, Rowenta či jakýkoliv jiný, postup se příliš neliší. Může se měnit v detailech v závislosti na způsobu otevírání krytu apod., ale princip uložení sáčku je vždy stejný. 
    date:    18. 11. 2019
    author:  Andrej Kašický