status:      ready
context:
  brands:
    - link:  aeg
      img:   https://chci-vysavat.cz/images/firms/aeg.jpg
      alt:   logo firmy AEG
      brand: AEG
    - link:  aeg
      img:   https://chci-vysavat.cz/images/firms/aeg.jpg
      alt:   logo firmy AEG
      brand: AEG
    - link:  aeg
      img:   https://chci-vysavat.cz/images/firms/aeg.jpg
      alt:   logo firmy AEG
      brand: AEG
    - link:  aeg
      img:   https://chci-vysavat.cz/images/firms/aeg.jpg
      alt:   logo firmy AEG
      brand: AEG
    - link:  aeg
      img:   https://chci-vysavat.cz/images/firms/aeg.jpg
      alt:   logo firmy AEG
      brand: AEG
    - link:  aeg
      img:   https://chci-vysavat.cz/images/firms/aeg.jpg
      alt:   logo firmy AEG
      brand: AEG
    - link:  aeg
      img:   https://chci-vysavat.cz/images/firms/aeg.jpg
      alt:   logo firmy AEG
      brand: AEG