status:      wip

context:
    class:   item--additional
    link:    /hepa-filtry/hepa-filtr-do-vysavacu-aeg/hepa-filtr-do-vysavacu-aeg-hf0001
    img:     https://chci-vysavat.cz/images/assets/pack/myThumb/HF0001.jpg
    img_alt: Fotka sáčku
    name:    Hepa filtr do vysavačů AEG (HF0001)
    info:    <span>SKLADEM</span> Expedujeme do 24 h