status:        prototype

context:
  breadcrumb:
    links:
    - link:    homepage
      text:    Domů
    - link:    znacky
      text:    Seznam značek
    - link:    electrolux
      text:    ELECTROLUX
    active:    S-BAG
  items:
  - link:      /electrolux/s-bag/baleni-vuni-do-vysavace-citronova
    class:     item--additional
    img_alt:   obrázek doplňku ELECTROLUX S-BAG
    img:       https://chci-vysavat.cz/images/assets/pack/myThumb/SC0001.jpg
    name:      Balení vůní do vysavače - citrónová
    info: "Balení obsahuje: <strong>(1 ks)</strong><br>
    Skladem:   <strong>ano</strong><br>
    Cena:      <strong>59.00 Kč</strong>"
    item_more: <button type="submit" name="submit[]" value="186303" class="btn btn-primary btn-sm">Vložit do košíku</button>
  - link:      /electrolux/s-bag/baleni-vuni-do-vysavace-citronova
    class:     item--additional
    img_alt:   obrázek doplňku ELECTROLUX S-BAG
    img:       https://chci-vysavat.cz/images/assets/pack/myThumb/SC0001.jpg
    name:      Balení vůní do vysavače - citrónová
    info: "Balení obsahuje: <strong>(1 ks)</strong><br>
    Skladem:   <strong>ano</strong><br>
    Cena:      <strong>59.00 Kč</strong>"
    item_more: <button type="submit" name="submit[]" value="186303" class="btn btn-primary btn-sm">Vložit do košíku</button>
  - link:      /electrolux/s-bag/baleni-vuni-do-vysavace-citronova
    class:     item--additional
    img_alt:   obrázek doplňku ELECTROLUX S-BAG
    img:       https://chci-vysavat.cz/images/assets/pack/myThumb/SC0001.jpg
    name:      Balení vůní do vysavače - citrónová
    info: "Balení obsahuje: <strong>(1 ks)</strong><br>
    Skladem:   <strong>ano</strong><br>
    Cena:      <strong>59.00 Kč</strong>"
    item_more: <button type="submit" name="submit[]" value="186303" class="btn btn-primary btn-sm">Vložit do košíku</button>
  - link:      /electrolux/s-bag/baleni-vuni-do-vysavace-citronova
    class:     item--additional
    img_alt:   obrázek doplňku ELECTROLUX S-BAG
    img:       https://chci-vysavat.cz/images/assets/pack/myThumb/SC0001.jpg
    name:      Balení vůní do vysavače - citrónová
    info: "Balení obsahuje: <strong>(1 ks)</strong><br>
    Skladem:   <strong>ano</strong><br>
    Cena:      <strong>59.00 Kč</strong>"
    item_more: <button type="submit" name="submit[]" value="186303" class="btn btn-primary btn-sm">Vložit do košíku</button>
  - link:      /electrolux/s-bag/baleni-vuni-do-vysavace-citronova
    class:     item--additional
    img_alt:   obrázek doplňku ELECTROLUX S-BAG
    img:       https://chci-vysavat.cz/images/assets/pack/myThumb/SC0001.jpg
    name:      Balení vůní do vysavače - citrónová
    info: "Balení obsahuje: <strong>(1 ks)</strong><br>
    Skladem:   <strong>ano</strong><br>
    Cena:      <strong>59.00 Kč</strong>"
    item_more: <button type="submit" name="submit[]" value="186303" class="btn btn-primary btn-sm">Vložit do košíku</button>
  - link:      /electrolux/s-bag/baleni-vuni-do-vysavace-citronova
    class:     item--additional
    img_alt:   obrázek doplňku ELECTROLUX S-BAG
    img:       https://chci-vysavat.cz/images/assets/pack/myThumb/SC0001.jpg
    name:      Balení vůní do vysavače - citrónová
    info: "Balení obsahuje: <strong>(1 ks)</strong><br>
    Skladem:   <strong>ano</strong><br>
    Cena:      <strong>59.00 Kč</strong>"
    item_more: <button type="submit" name="submit[]" value="186303" class="btn btn-primary btn-sm">Vložit do košíku</button>
  - link:      /electrolux/s-bag/baleni-vuni-do-vysavace-citronova
    class:     item--additional
    img_alt:   obrázek doplňku ELECTROLUX S-BAG
    img:       https://chci-vysavat.cz/images/assets/pack/myThumb/SC0001.jpg
    name:      Balení vůní do vysavače - citrónová
    info: "Balení obsahuje: <strong>(1 ks)</strong><br>
    Skladem:   <strong>ano</strong><br>
    Cena:      <strong>59.00 Kč</strong>"
    item_more: <button type="submit" name="submit[]" value="186303" class="btn btn-primary btn-sm">Vložit do košíku</button>