status:          wip

context:
    articles:
      - img:     /img/poradna-img-01.jpg
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Jak vyměnit sáček ve vysavači
        text:    Obdrželi jste zásilku sáčků VACS? V několika krocích vám poradíme, jak vyměnit sáčky do vysavače a jak vyměnit filtr ve vysavači. Není to nic těžkého a zvládne to každý. Ať už máte vysavač Eta, Zelmer, Rowenta či jakýkoliv jiný, postup se příliš neliší. Může se měnit v detailech v závislosti na způsobu otevírání krytu apod., ale princip uložení sáčku je vždy stejný. 
        date:    18. 11. 2019
        author:  Andrej Kašický
      - img:     https://picsum.photos/500/250?random=10
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Polarised multimedia internet solution
        text:    |-
          In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

          Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.

          Sed ante. Vivamus tortor. Duis mattis egestas metus.
        date:    29.1.2019
        author:  Sloan Boddy
      - img:     https://picsum.photos/500/250?random=1
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Monitored well-modulated portal
        text:    |-
          In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

          Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.
        date:    12.7.2019
        author:  Nikoletta Digance
      - img:     https://picsum.photos/500/250?random=2
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Visionary asynchronous circuit
        text:    |-
          Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

          Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
        date:    20.6.2019
        author:  Raimund Mylechreest
      - img:     https://picsum.photos/500/250?random=3
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Reverse-engineered asynchronous moratorium
        text:    |-
          In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

          Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

          Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.
        date:    25.10.2019
        author:  Babita Lethcoe
      - img:     https://picsum.photos/500/250?random=4
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Synergized 24 hour internet solution
        text:    |-
          Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

          Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

          Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.
        date:    5.6.2019
        author:  Meta MacAllister
      - img:     https://picsum.photos/500/250?random=5
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Synergistic cohesive approach
        text:    |-
          Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

          Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

          Fusce consequat. Nulla nisl. Nunc nisl.
        date:    5.6.2019
        author:  Rocky Kerbey
      - img:     https://picsum.photos/500/250?random=6
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Re-contextualized zero defect time-frame
        text:    Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi
          ut odio.
        date:    28.1.2019
        author:  Vidovic Zum Felde
      - img:     https://picsum.photos/500/250?random=7
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Upgradable 3rd generation data-warehouse
        text:    |-
          Phasellus in felis. Donec semper sapien a libero. Nam dui.

          Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

          Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.
        date:    24.9.2019
        author:  Maurise Kohring
      - img:     https://picsum.photos/500/250?random=8
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Profound directional productivity
        text:    Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.
          Vivamus vel nulla eget eros elementum pellentesque.
        date:    21.10.2019
        author:  Menard Tortice
      - img:     https://picsum.photos/500/250?random=9
        img_alt: Fotka článku
        link:    poradna-detail
        title:   Cross-group holistic superstructure
        text:    Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet,
          pulvinar sed, nisl. Nunc rhoncus dui vel sem.
        date:    20.4.2019
        author:  Wally Langwade

